name = "SISREMO"
uuid = "5e8a1ad8-f587-407c-a5f9-7fd46a1a5d7a"
version = "0.1.0"
authors = ["wester <rolf.wester@mailbox.org>"]

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PhysConst = "5fb906b7-6b74-4262-a47b-bfc7830f13d6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Arrow = "2.8.0"
CSV = "0.10.15"
CurveFit = "1.1.0"
DataFrames = "1.7.0"
DataStructures = "0.18.20"
Dates = "1.11.0"
FiniteDifferences = "0.12.32"
HDF5 = "0.17.2"
HTTP = "1.10.15"
Interpolations = "0.15.1"
JLD = "0.13.5"
JSON3 = "1.14.1"
Logging = "1.11.0"
LoggingExtras = "1.2.0"
NLopt = "1.1.3"
Optim = "1.11.0"
Optimization = "4.1.2"
OptimizationNLopt = "0.3.2"
OptimizationOptimJL = "0.4.1"
OrderedCollections = "1.8.0"
Printf = "1.11.0"
PyPlot = "2.11.6"
SQLite = "1.6.1"
Statistics = "1.11.1"
StringEncodings = "0.3.7"
Tables = "1.12.1"
TimeZones = "1.22.0"
